### ISSUE TITLE
ДЗ - исправить разметку заданий рубежного контроля

### ISSUE THREAD

**Issue by sbannikov** [sbannikov/csharpbmstu20#1]
Исправить разметку (HTML/CSS) заданий рубежного контроля так, чтобы колонки кода, исправленного кода и примечаний к коду имели бы примерно одинаковый размер.

**Comment by Aerdayne** [comment]
https://github.com/sbannikov/csharpbmstu20/pull/2

**Comment by sbannikov** [comment]
Домашнее задание принято
